services:
  db:
    image: mariadb:10.11
    container_name: bbm_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password_db
      MYSQL_DATABASE: bpf_asset_system
      MYSQL_USER: bpf_user
      MYSQL_PASSWORD: bpf_pass
    ports:
      - "3307:3306"
    volumes:
      - bbm_db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    networks:
      - default

  web:
    build: .
    container_name: bbm_web
    ports:
      - "5001:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
    environment:
      - FLASK_DEBUG=0
      - DB_HOST=db
      - DB_USER=bpf_user
      - DB_PASSWORD=bpf_pass
      - DB_NAME=bpf_asset_system
      - DB_POOL_SIZE=15
      - SECRET_KEY=bpf_bbm_super_secret_production_key_2026_indonesia
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - default            # Terhubung ke bbm_mariadb
      - nextcloud_net      # Terhubung ke nextcloud_nginx

volumes:
  bbm_db_data:
  
networks:
  default:
  nextcloud_net:
    external: true
    name: nextcloud_net